name: update readme

on:
  schedule:
  - cron: 0 * * * *
  
  workflow_dispatch:

jobs:
  fetch-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm init -y
        npm install puppeteer

    - name: Fetch HTML using Puppeteer
      run: |
        # Create a Node.js script to fetch the HTML content using Puppeteer
        echo "const puppeteer = require('puppeteer');" > fetchHtml.js
        echo "async function run() {" >> fetchHtml.js
        echo "  const browser = await puppeteer.launch();" >> fetchHtml.js
        echo "  const page = await browser.newPage();" >> fetchHtml.js
        echo "  await page.goto('http://anything.wuaze.com');" >> fetchHtml.js  # Replace with your target URL
        echo "  const content = await page.content();" >> fetchHtml.js
        echo "  require('fs').writeFileSync('README.md', content);" >> fetchHtml.js
        echo "  await browser.close();" >> fetchHtml.js
        echo "}" >> fetchHtml.js
        echo "run();" >> fetchHtml.js

        node fetchHtml.js

    - name: Commit changes to README.md
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Update README from website content"
        git push
